openapi: 3.0.3
info:
  title: Google Search Plugin API
  description: A Google Search plugin for chat-gpt
  version: 1.0.0

servers:
  - url: http://localhost:3000
paths:
  /api/search:
    get:
      operationId: searchGet
      summary: Search Google and fetch HTML content
      description: |
        Searches Google using the provided query and returns the search results, along with the inner text of the first link.
        The first five search results include a summary of the HTML content, while the first three have the entire HTML content returned in the response.
      parameters:
        - name: q
          in: query
          description: Search query
          required: true
          schema:
            type: string
          example: github
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        title:
                          type: string
                          description: The title of the search result
                        link:
                          type: string
                          format: uri
                          description: The URL of the search result
                        snippet:
                          type: string
                          description: A summary of the HTML content of the search result (available for the first five results)
                        
                example:
                  results:
                    - title: 'GitHub:' Let's build from here · GitHub
                      link: https://www.github.com/
                      snippet: GitHub is where over 100 million developers shape the future of software, together. Contribute to the open source community, manage your Git repositories, ...
                    - title: GitHub - Wikipedia
                      link: https://en.wikipedia.org/wiki/GitHub
                      snippet: GitHub, Inc is an Internet hosting service for software development and version control using Git. It provides the distributed version control of Git plus ...
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message
                example:
                  error: No query provided
        'default':
          description: Error fetching search results
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message
                example:
                  error: Error fetching search results